### ISSUE TITLE
Consider making session a SimpleNamespace

### ISSUE THREAD

**Issue by jbellis** [AnswerDotAI/fasthtml#204]
It's just friendlier than a dict with string keys.

**Comment by jph00** [comment]
Use fastcore's dict2obj if you prefer that.

**Comment by jbellis** [comment]
Are you open to a patch that wraps the Starlette session in an AttrDict?

**Comment by jph00** [comment]
Hmm interesting idea. Could even do that to `scope` as well? I'm open to it -- feel free to give it a try, but test it lots because I'm slightly nervous that it could have some weird side effects (I don't know why I'm nervous about it... guess it's probably gonna be fine thinking more carefully...) I guess check that home-fasthtml, fh-about, stuff in fasthtml-example etc still all work ok.

**Comment by jbellis** [comment]
Okay, I'll give it a shot.

> check that home-fasthtml, fh-about, stuff in fasthtml-example etc still all work ok

What repo are the first two in?  I don't see any "home" or "about" files in this one or fasthtml-example.

**Comment by jph00** [comment]
Those are all repo names in the answerdotai org.
