### ISSUE TITLE
Session can't encode objects it can decode

### ISSUE THREAD

**Issue by jbellis** [AnswerDotAI/fasthtml#226]
I noticed it with UUIDs, other types may also be affected.
```
from uuid import UUID
from fasthtml.common import *

app = FastHTML()

@app.get("/")
def index(session, item_id: UUID):
    session['item_id'] = item_id

serve()
```
```
curl -X GET "localhost:5001/?item_id=36621c53-55c3-11ef-b14b-c45ab1ddc9ad"
```
Result:
```
TypeError: Object of type UUID is not JSON serializable
```

**Comment by palomino79** [comment]
This is less an issue with FastHTML and more an issue with Starlette, which FastHTML is built on top of. Specifically, FastHTML overrides Starlette's SessionMiddleware in order to wrap the initial session data in an AttrDict. On sending session data, Starlette serializes the session object via a call to `json.dumps`, which examines the type of object it's serializing and raises a TypeError if it finds something in it that is not one of the object types it knows how to work with. As such, I see two practical solutions to this problem. 

1. Require developers to cast whatever object they want to persist in session data to something they know can be handled by `json.dumps`. In this case, that would be simply casting the UUID to a string. Or...
2. Overriding the rest of the SessionMiddleware's  `__call__` method to integrate a more flexible serialization function inside of `send_wrapper` that would attempt to convert the objects it was passed into known serializable data types, before ultimately being passed to `json.dumps` and proceeding with the rest of the expected logic of that function.

If a project maintainer could let me know whether or not the second option is in line with the general design philosophy of this project (or, more generally, if such a change would be desirable), I'd be willing to attempt the necessary changes to accommodate the second option and then open a PR for it.

**Comment by jph00** [comment]
> If a project maintainer could let me know whether or not the second option is in line with the general design philosophy of this project (or, more generally, if such a change would be desirable), I'd be willing to attempt the necessary changes to accommodate the second option and then open a PR for it.

We do have a (slightly) custom `_SessionMiddleware` now, so there's certainly room to experiment here. Maybe give it a go and see if you're able to come up with something that feels simple, consistent, and intuitive? (If we can't, I'm fine telling folks to just serialize things manually.)
