### ISSUE TITLE
[BUG] Session appears to not shared between HTTP endpoints and websockets

### ISSUE THREAD

**Issue by lianggecm** [AnswerDotAI/fasthtml#601]
If you're reporting a bug, please continue with this template.

**Describe the bug**
Session sets in HTTP end points and websockets have different values.

**Minimal Reproducible Example**
Provide a minimal code snippet that reproduces the issue. This is crucial for us to understand and fix the bug quickly.

```python
from fasthtml.common import *
#from fh_frankenui.core import *
import sys
import uuid

app, rt = fast_app(
    pico=True,
    hdrs=(
        Script(src="https://unpkg.com/htmx.org/dist/ext/ws.js"),  # Add WebSocket extension
        ),
)
@rt("/")
async def home(session):
    old_session_id = session.get('session_id', None)
    # Get a new session_id
    session['session_id'] = str(uuid.uuid4())
    return Div(P(f"Original session_id: {old_session_id}"),
               P(f"New session_id created in Main: {session['session_id']}"),
               Button("Settings", hx_get="/settings", hx_target="#settings-container"),Div(id="settings-container"),
               Form(Input(name="msg"), Button("Send to ws"), hx_ext="ws",
            ws_connect="/ws-test",ws_send=True,), Div(id="chat-container"))


@rt('/settings')
def get(session):
    session_id_in = session.get('session_id', None)
    session['session_id'] = str(uuid.uuid4())

    return Div(P(f"Session_id sent to settings: {session_id_in}"), P(f"New session_id created in settings: {session.get('session_id', None)}"), id="settings-container")
    
@app.ws('/ws-test')
async def ws(msg:str, send, session):
    session_id_in = session.get('session_id', None)
    session['session_id'] = str(uuid.uuid4())
    await send(Div(P(f"Session_id sent to ws: {session_id_in}"),P(f"New session_id set in ws: {session.get('session_id', None)}"), id="chat-container"))

```

**Expected behavior**
In this example I fist set session_id in "/". Then change the session_id in "/settings". **Afterwards**, I send the session to "/ws" and change the values of session_id. The Session_id sent to the "/ws" websocket should be the session_id value set in the "/settings" endpoint. However, as seen in the picture here, the session_id sent to the "/ws" is still the same as the value that was set in "/".

![image](https://github.com/user-attachments/assets/f7b143ea-586a-488c-afa5-cb1b475441b6)

Further clicks on the two buttons would show that session_id sets in either endpoints doesn't exchange/share at all.

**Environment Information**
Please provide the following version information:
- fastlite version: 0.0.13
- fastcore version: 1.7.19
- fasthtml version: 0.10.1

**Confirmation**
Please confirm the following:
- [ X] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [ X] I have provided a minimal reproducible example
- [ X] I have included the versions of fastlite, fastcore, and fasthtml
- [ X] I understand that this is a volunteer open source project with no commercial support.

**Additional context**

**Screenshots**

**Comment by jph00** [comment]
This appears to be related to starlette, not fasthtml (fasthtml by default makes starlette sessions available) so you should use the starlette issue tracker for help with that.

**Comment by gimbo** [comment]
I think this should be revisited: AFAICS it's _not_ something Starlette can fix.  I'll explain why I think that, and make some suggestions.

## The Short Version

Here's the core of the problem: cookies can't be read or written over a WebSocket connection once it's been set up.  You simply _can't_ update a cookie — or notice an update to a cookie — over a WebSocket.  So mutable cookies and WebSockets are fundamentally incompatible.  If you store changing session state in cookies, WebSockets can’t participate.  Starlette can't fix this; arguably the way it exposes session cookies is broken in that it doesn't make this limitation clear, but it can't make the problem go away or work around it.

Right now this is a lurking gotcha for FastHTML users; it should be called out if not actively prevented — but there's no way to _solve_ this issue while still using mutable cookies to store session state.  WebSockets or mutable session cookies: pick one.

I suggest that The Right Thing for FastHTML to do is support and encourage server-side session state; at session start you create an ID, store it in a cookie, _and never modify that cookie during the session_.  It's just a key into state you store on the server, whether in memory, on the filesystem, or in something like Redis.  Such sessions (and their updates) can be shared properly between HTTP and WebSocket routes.

There are other good reasons to store session data server-side: at the very least you won't hit cookie size limits, but it also allows some pretty useful stuff which is harder or impossible to achieve with the current approach.

## The Long Version

### This is not an issue with Starlette

A cookie can be set during a WebSocket handshake, but after the WebSocket handshake completes, cookies can’t be read or updated over that connection. That is, the browser sends its cookies once — in the initial HTTP Upgrade request — and the server can set cookies only in the `101 Switching Protocols` response.  Once the protocol switches from HTTP to WebSocket, no further HTTP headers (including `Set-Cookie`) are exchanged.

So: Starlette **can’t** make session updates behave identically between HTTP and WebSocket connections, because it can't propagate session updates over WebSocket at all (in either direction).  That's not a Starlette bug; it's a WebSocket limitation.

If you run @lianggecm's [example code](https://github.com/AnswerDotAI/fasthtml/issues/601#issue-2731942968) and watch cookie state via your browser's web dev UI, you'll see that clicks on the "Settings" button do indeed modify the cookie, but clicks on the "Send to ws" button **do not**.  That's a reflection of the fact that WebSocket connections can't update cookies; when the `ws-test` handler updates `session['session_id']`, that update happens in memory on server-side (in the `scope` attribute of a `WebSocket` object defined by `Starlette`), but the update simply can't propagate to the browser/the cookie.

### Suggestions for FastHTML

If we accept that this can't, in fact, be fixed upstream, what can be done?  Some suggestions...

* **Do nothing**

    Always an option. 🙂

* **Documentation improvements**

    If nothing else, the FastHTML documentation should be updated to call out this gotcha.  In particular, in [the section on Session data in WebSockets](https://www.fastht.ml/docs/explains/websockets.html#session-data-in-websockets), we have:

    > Session data is shared between standard HTTP routes and Websockets.

    That's true _until the session is mutated_ (in either place) — as soon as that happens, the "sharing" breaks down, in both directions.

* **Forbid modifying `session` in WebSocket routes**

    An obvious "fix" is to disallow `session` updates in WebSocket routes — take the plain dict obtained from Starlette, and turn it into something immutable (e.g. `types.MappingProxyType`); I think this would involve a small change to `fasthtml/core.py`.

    Alas, I had to write "fix" in quotes because this doesn't solve the problem that when an HTTP route updates the session/cookie, the update doesn't get reflected back to the WebSocket "session".

    (Also, it's a breaking change, for little gain. 🤷‍♂️)

* **Store session data on the server side**

    If FastHTML wants to present a truly unified way of dealing with state across HTTP and WebSocket — and particularly if FastHTML wants to do so in an awesome way — the opportunity is to support (and encourage the use of) server-side session storage.

    There are lots of ways to do that of course, but an obvious approach would be to use Starlette's session machinery to store a session ID (and nothing else) in a cookie at the start of a session, and _never change it_.  Because the ID never changes, your HTTP and WebSocket routes both get the same ID, so they both refer to the same (server-side) session.

    I half-expected there to be a de facto standard Starlette server-side session library but AFAICS there isn't — but there are options and examples out there.

### NiceGUI happens to do this really well

Final thing: around the time I discovered FastHTML I also looked at NiceGUI, and while I much prefer FastHTML in almost every respect, [NiceGUI's session/storage machinery](https://nicegui.io/documentation/storage) is exemplary, IMHO.  It supports different scopes for different purposes (e.g. client scope for anything which should be automatically cleaned up when they close that tab, global scope for stuff like config, counts, etc.), and its "user scoped" storage does the same job as session cookies, but better... Out of the box you get automatic state propagation _across tabs/windows_ — I had this working on the second NiceGUI example I ran, which was a real "wow" moment[^1].  AFAICS the underlying storage implementation is not outlandishly complex — key pieces seem to be [`ObservableDict`](https://github.com/zauberzeug/nicegui/blob/83f4d16539741c4851308117e2af48e8620ba7f3/nicegui/observables.py#L75), [`PersistentDict`](https://github.com/zauberzeug/nicegui/blob/83f4d16539741c4851308117e2af48e8620ba7f3/nicegui/persistence/persistent_dict.py#L6) (and its FS/Redis versions), and [`RequestTrackingMiddleware`](https://github.com/zauberzeug/nicegui/blob/83f4d16539741c4851308117e2af48e8620ba7f3/nicegui/storage.py#L23).

Now, I'm not suggesting lifting the code or even the design wholesale — but I think it's a really good example of Doing This Right. If FastHTML's serious about wanting to be "[the easiest way to create scalable, powerful, rich applications](https://fastht.ml/about/vision)", I'd argue better session support will be needed — and here's one good model.

Thanks for an awesome framework, and I hope this is helpful.

[^1]: The automatic state propagation stuff uses NiceGUI's [binding machinery](https://nicegui.io/documentation/section_binding_properties) but it's sooooo sweet and it's not too hard to imagine replicating that functionality under FastHTML via SSE or maybe [Broadcast Channels](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API).

**Comment by jph00** [comment]
@gimbo thanks for the very thoughtful analysis.

I'm leaning towards option 1. :) FastHTML on the whole is meant to be a fairly low level thing which you can add whatever you like on top of. Personally, I generally do state just the way you say -- but the actual machinery of how to handle that is going to vary depending on lots of stuff. I'd often use a sqlite table, for instance.

I'm certainly open to a docs PR as you suggest, although it's verging into the "document how the web works" territory -- and we can't document everything about how the web works! ;)

An `fh-serversession` pypi lib that provides this feature would be most welcome, I think, but I don't think it's an obvious thing to put in core.
