### ISSUE TITLE
Material Based Components 

### ISSUE THREAD

**Issue by jakre1234** [AnswerDotAI/fasthtml#98]
Can we please have pre made components, for backend devs like me writing CSS and making UI is whole another level of pain in the a$$, can we have pre made components like navbar,sidebar,heading,columns,rows etc etc like they have in flutter

Thanks and Regards,.

**Comment by jakre1234** [comment]
Or maybe a community library likde pub.dev , where people can share there ready to use components for devs like us who can chain different components together to build up a quick prototype

**Comment by pydanny** [comment]
This is in the works. 😄

**Comment by jakre1234** [comment]
Thank you so much, finally I have found the perfect python based framework for my projects. You won't belive how many different frameworks I have hoped on but nothing felt good as this one, from streamlit to pyscript to mesop to Flet to reflex.dev I have tried each one of them and nothing fit my coding style, I totally suck at UI and have literally zero interest in writing CSS and centering a div by myself...FastHTMX just seems perfect(of course it got the HTMX rizzz), just a good curated list of custom components(I love flutter's pub.dev for this) and we will have the perfect python web framework :)
Once again, thanks for this perfect framework :fist_raised:

**Comment by ncoop57** [comment]
Still very much under development, but please checkout https://github.com/AnswerDotAI/fh-bootstrap for using bootstrap components and styling @jakre1234

**Comment by jpiabrantes** [comment]
@pydanny 

When you say "this is in the works 😄" are you referring to Material Components or replicating Flutter widgets for HTMLFast or both?

I 100% agree with @jakre1234. I think Flutter has the best components (widgets) because:

1. All the arguments are named and typed. You understand how to use a Component just by looking at its signature. There is no need to memorise specific strings for class names or rely on catch-all kwargs.
2. The arguments give you all the flexibility flexibility. It's easy to map Figma to UI or even skip Figma entirely.

I’d love to learn more about what’s in the works so I can decide what to build for my projects!
